--------TABLES--------
CREATE TABLE IF NOT EXISTS torneos(
    torneo_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar(30) NOT NULL CHECK (nombre <> ''),
    lugar varchar(50),
    fecha_inicio date,
    fecha_fin date,
    cantidad_equipos integer,
    jugadores_por_equipo integer,
    observaciones text
);

CREATE TABLE IF NOT EXISTS etapas(
    etapa_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar(30) NOT NULL CHECK (nombre <> ''),
    anterior_etapa_id integer REFERENCES etapas(etapa_id),
    siguiente_etapa_id integer REFERENCES etapas(etapa_id),
    torneo_id integer REFERENCES torneos(torneo_id)
);

CREATE TABLE IF NOT EXISTS partidos(
    partido_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fecha_hora date,
    orden_partido integer,
    estado varchar(30),
    puntos_equipo1 integer,
    puntos_equipo2 integer,
    equipo1_id integer REFERENCES equipos(equipo_id),
    equipo2_id integer REFERENCES equipos(equipo_id),
    etapa_id integer REFERENCES etapas(etapa_id)
);

CREATE TABLE IF NOT EXISTS equipos(
    equipo_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar(30) NOT NULL CHECK (nombre <> ''),
    pais_representado varchar(30),
    club varchar(30),
    entrenador varchar(30)
);

CREATE TABLE IF NOT EXISTS jugadores(
    jugador_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar(30) NOT NULL CHECK (nombre <> ''),
    posicion varchar(30),
    equipo_id integer REFERENCES equipos(equipo_id)
);

--------SELECTS--------
SELECT * FROM torneos ORDER BY torneo_id;
SELECT * FROM etapas ORDER BY etapa_id;
SELECT * FROM partidos ORDER BY partido_id;
SELECT * FROM equipos ORDER BY equipo_id;
SELECT * FROM jugadores ORDER BY jugador_id;

--------ALTER/DROP/DELETE--------
--DELETE FROM etapas;
--DROP TABLE partidos;
--------INSERTS/UPDATES--------
--Torneos
INSERT INTO torneos (nombre, lugar, fecha_inicio, fecha_fin, cantidad_equipos, jugadores_por_equipo, observaciones)
VALUES ('Copa de leche', 'Cancha de River Plate', '2021/03/02', '2021/04/03', 16, 11, 'Son todos gatos');
INSERT INTO torneos (nombre, lugar, fecha_inicio, fecha_fin, cantidad_equipos, jugadores_por_equipo, observaciones)
VALUES ('Copa Libertadores', 'Cancha de Boca Jrs', '2021/03/07', '2021/04/08', 16, 11, 'Son todos giles');
INSERT INTO torneos (nombre, lugar, fecha_inicio, fecha_fin, cantidad_equipos, jugadores_por_equipo, observaciones)
VALUES ('Copa Mundial', 'Japón', '2021/03/09', '2021/04/10', 8, 11, 'Son todos re gatos');
--Etapas
INSERT INTO etapas (nombre, anterior_etapa_id, siguiente_etapa_id, torneo_id)
VALUES ('Etapa 1', null, null, 1);
INSERT INTO etapas (nombre, anterior_etapa_id, siguiente_etapa_id, torneo_id)
VALUES ('Etapa 2', 1, null, 1);
INSERT INTO etapas (nombre, anterior_etapa_id, siguiente_etapa_id, torneo_id)
VALUES ('Etapa 3', 2, null, 1);
--Partidos
INSERT INTO partidos (fecha_hora, orden_partido, estado, puntos_equipo1, puntos_equipo2, equipo1_id, equipo2_id, etapa_id)
VALUES ('2021/05/05', 1, 'pendiente', 10, 5, 1, 2, 1);
INSERT INTO partidos (fecha_hora, orden_partido, estado, puntos_equipo1, puntos_equipo2, equipo1_id, equipo2_id, etapa_id)
VALUES ('2021/05/06', 2, 'en juego', 11, 10, 2, 3, 1);
INSERT INTO partidos (fecha_hora, orden_partido, estado, puntos_equipo1, puntos_equipo2, equipo1_id, equipo2_id, etapa_id)
VALUES ('2021/05/07', 3, 'terminado', 12, 15, 3, 1, 1);
--Equipos
INSERT INTO equipos (nombre, pais_representado, club, entrenador)
VALUES ('Tigres', 'Argentina', 'Patronato', 'Papa Juan Pablo II');
INSERT INTO equipos (nombre, pais_representado, club, entrenador)
VALUES ('Leones', 'Argentina', 'Boca Jrs', 'Don Quijote');
INSERT INTO equipos (nombre, pais_representado, club, entrenador)
VALUES ('Pescaditos', 'Argentina', 'River Plate', 'Jebus');
--Jugadores
INSERT INTO jugadores (nombre, posicion, equipo_id)
VALUES ('Marcelo Gomez', '10', 1);
INSERT INTO jugadores (nombre, posicion, equipo_id)
VALUES ('Juan Perez', '1', 2);
INSERT INTO jugadores (nombre, posicion, equipo_id)
VALUES ('San Pedro', '4', 3);


