--------TABLES--------

CREATE TABLE IF NOT EXISTS equipos(
    equipoid integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar(30) NOT NULL CHECK (nombre <> ''),
    paisRepresentado varchar(30),
    club varchar(30),
    entrenador varchar(30)
);

CREATE TABLE IF NOT EXISTS etapas(
    etapaid integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar(30) NOT NULL CHECK (nombre <> ''),
    anteriorEtapaid integer REFERENCES etapas(etapaid),
    siguienteEtapaid integer REFERENCES etapas(etapaid)
);

CREATE TABLE IF NOT EXISTS jugadores(
    jugadorid integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar(30) NOT NULL CHECK (nombre <> ''),
    equipoid integer,
    posicion varchar(30)
);

CREATE TABLE IF NOT EXISTS partidos(
    partidoid integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fechaHora date,
    equipo1id integer REFERENCES equipos(equipoid),
    equipo2id integer REFERENCES equipos(equipoid),
    puntosEquipo1 integer,
    puntosEquipo2 integer,
    ordenPartido integer,
    estado varchar(30),
    torneoid integer REFERENCES torneos(torneoid)
);

CREATE TABLE IF NOT EXISTS torneos(
    torneoid integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar(30) NOT NULL CHECK (nombre <> ''),
    lugar varchar(50),
    fechaInicio date,
    fechaFin date,
    jugadoresPorEquipo integer,
    observaciones text
);

--------SELECTS--------

SELECT * FROM equipos;
SELECT * FROM etapas ORDER BY etapaid;
SELECT * FROM jugadores;
SELECT * FROM partidos;
SELECT * FROM torneos;

--------ALTER TABLE--------

ALTER TABLE jugadores ADD FOREIGN KEY (equipoid) REFERENCES equipos(equipoid);

ALTER TABLE etapas ADD COLUMN torneoid int;
ALTER TABLE etapas ADD FOREIGN KEY (torneoid) REFERENCES torneos(torneoid);

ALTER TABLE partidos ADD COLUMN etapaid int;
ALTER TABLE partidos ADD FOREIGN KEY (etapaid) REFERENCES etapas(etapaid);

--DROP TABLE partidos;
--DROP TABLE etapas;
--DELETE FROM etapas

--------INSERTS/UPDATES--------
--Equipos
INSERT INTO equipos (nombre, paisRepresentado, club, entrenador)
VALUES ('Tigres', 'Argentina', 'Patronato', 'Papa Juan Pablo II');
INSERT INTO equipos (nombre, paisRepresentado, club, entrenador)
VALUES ('Leones', 'Argentina', 'Boca Jrs', 'Don Quijote');
INSERT INTO equipos (nombre, paisRepresentado, club, entrenador)
VALUES ('Pescaditos', 'Argentina', 'River Plate', 'Jebus');
--Etapas
INSERT INTO etapas (nombre, siguienteEtapaid, anteriorEtapaid)
VALUES ('Etapa 1', null, null);
INSERT INTO etapas (nombre, siguienteEtapaid, anteriorEtapaid)
VALUES ('Etapa 2', null, 1);
INSERT INTO etapas (nombre, siguienteEtapaid, anteriorEtapaid)
VALUES ('Etapa 3', null, 2);
--
UPDATE etapas 
SET siguienteEtapaid = 2
WHERE etapaid = 1;
UPDATE etapas 
SET siguienteEtapaid = 3
WHERE etapaid = 2;
--Jugadores
INSERT INTO jugadores (nombre, equipoid, posicion)
VALUES ('Marcelo Gomez', 1, '10');
INSERT INTO jugadores (nombre, equipoid, posicion)
VALUES ('Juan Perez', 2, '1');
INSERT INTO jugadores (nombre, equipoid, posicion)
VALUES ('San Pedro', 3, '4');
--Partidos
INSERT INTO partidos (fechaHora, equipo1id, equipo2id, puntosEquipo1, puntosEquipo2, ordenPartido, estado, torneoid)
VALUES ('2021/05/05', 1, 2, 1, 4, 1,  'pendiente', 1);
INSERT INTO partidos (fechaHora, equipo1id, equipo2id, puntosEquipo1, puntosEquipo2, ordenPartido, estado, torneoid)
VALUES ('2021/05/06', 2, 1, 3, 2, 2,  'en juego', 2);
INSERT INTO partidos (fechaHora, equipo1id, equipo2id, puntosEquipo1, puntosEquipo2, ordenPartido, estado, torneoid)
VALUES ('2021/05/07', 2, 3, 0, 5, 3,  'terminado', 3);
--Torneos
INSERT INTO torneos (nombre, lugar, fechaInicio, fechaFin, jugadoresPorEquipo, observaciones)
VALUES ('Copa de leche', 'Cancha de River Plate', '2021/03/02', '2021/04/03', 11, 'Son todos gatos');
INSERT INTO torneos (nombre, lugar, fechaInicio, fechaFin, jugadoresPorEquipo, observaciones)
VALUES ('Copa Libertadores', 'Cancha de Boca Jrs', '2021/03/07', '2021/04/08', 11, 'Son todos giles');
INSERT INTO torneos (nombre, lugar, fechaInicio, fechaFin, jugadoresPorEquipo, observaciones)
VALUES ('Copa Mundial', 'Japón', '2021/03/09', '2021/04/10', 11, 'Son todos re gatos');
